### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by yfhuang7** [NCAR/rwrfhydro#96]
Hi,

I met loading error while installing rwrfhydro, but I don't understand the error message (see below), it seems like it's the system problem. What can I do to install rwrfhydro successfully? Do I need certain version of R?

Thanks!
yufen

devtools::install_github("NCAR/rwrfhydro")
Downloading GitHub repo NCAR/rwrfhydro@master
from URL https://api.github.com/repos/NCAR/rwrfhydro/zipball/master
Installing rwrfhydro
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL "C:/Users/Yu-Fen  \
  Huang/AppData/Local/Temp/RtmpigF4t3/devtools47c813eb6557/NCAR-rwrfhydro-5a0b83e"  \
  --library="C:/Users/Yu-Fen Huang/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'rwrfhydro' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'rwrfhydro' in namespaceExport(ns, exports):
 undefined exports: GetNldas2
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'rwrfhydro' in namespaceExport(ns, exports):
 undefined exports: GetNldas2
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Yu-Fen Huang/Documents/R/win-library/3.4/rwrfhydro'
Installation failed: Command failed (1)

**Comment by jmccreight** [comment]
Hi all, sorry about this. I didnt notice it last time I updated. 
Would someone mind cloning the repo and devtools:install() it? If that fails, then remove the GetNldas2 line from the NAMESPACE file in the top level and try again. Roxygen sometimes leaves stale bits in there. 

I could try this, but it will be several days. My R legs are rusty at the moment.

**Comment by ChuliangXiao** [comment]
@jmccreight 
Yes, it worked as you suggested.
After `GetNldas2` is removed from `NAMESPACE` of the repo, `rwrfhydro` is installed by `devtools::install("rwrfhydro")`.

**Comment by yfhuang7** [comment]
Yes, I can install it after removing the GetNldas2 line from the NAMESPACE. Thanks! :D

**Comment by jmccreight** [comment]
Who wants submit a pull request of the fix so I dont have to redo it? 
If your local rwrfhydro is a clone of your fork (e.g. `git remote -v` shows `origin	git@github.com:<YOURFORK>/wrf_hydro_dart.git`)  then commit and push the change to your fork and issue a pull request. 
If your local rwrfhydro is clone of upstream (e.g. `git remote -v` shows `origin	git@github.com:NCAR/wrf_hydro_dart.git`), then I can offer you more assistance, if you are game to try.

**Comment by jmccreight** [comment]
thanks yufen! for PR #97.
